plugins:
  - rubocop-rake
  - rubocop-minitest

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  SuggestExtensions: false

Style/FrozenStringLiteralComment:
  Exclude:
    - exe/*

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/RegexpLiteral:
  EnforcedStyle: percent_r

Style/HashSyntax:
  EnforcedShorthandSyntax: consistent

Layout/FirstMethodArgumentLineBreak:
  Enabled: true

Layout/MultilineMethodArgumentLineBreaks:
  Enabled: true
  AllowMultilineFinalElement: false

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/MultilineHashBraceLayout:
  EnforcedStyle: new_line

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/BlockDelimiters:
  EnforcedStyle: line_count_based

Style/Documentation:
  Enabled: false

Metrics/ClassLength:
  Exclude:
    - lib/stimulus_plumbers/themes/**/*.rb
    - test/**/*_test.rb

Metrics/ModuleLength:
  Exclude:
    - lib/stimulus_plumbers/components/plumber/stimulus_registry.rb

Style/DocumentDynamicEvalDefinition:
  Exclude:
    - lib/stimulus_plumbers/components/plumber/views.rb

Metrics/MethodLength:
  Exclude:
    - lib/stimulus_plumbers/themes/**/*.rb
    - test/**/*_test.rb

Minitest/MultipleAssertions:
  Enabled: false
